
SELECT PO.CONTEUDO AS 'Conteúdo da postagem',
PE.NOME AS 'Autor',
COUNT(LI.ID) AS 'Likes',
(SELECT PESSOA.NOME FROM PESSOA WHERE ID = LI.ID_PESSOA) AS 'Quem curtiu',
(SELECT PESSOA.NOME FROM PESSOA WHERE ID = CO.ID_PESSOA) AS 'Quem comentou',
(SELECT PESSOA.NOME FROM PESSOA WHERE ID = CP.ID_PESSOA) AS 'Quem compartilhou'

FROM POSTAGEM AS PO
INNER JOIN PESSOA AS PE
ON PO.ID_PESSOA = PE.ID

INNER JOIN LIKE_POSTAGEM AS LI
ON LI.ID_POSTAGEM = PO.ID

INNER JOIN COMENTARIO AS CO
ON CO.ID_POSTAGEM = PO.ID

INNER JOIN COMPARTILHAMENTO AS CP
ON CP.ID_POSTAGEM = PO.ID;

